name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
            auth-service,
            common-service,
            cache-service,
            generate-service,
            tag-service,
            note-service,
            user-service,
            notification-service,
            tag-management-service,
            note-management-service,
            user-management-service,
            notification-management-service,
          ] # Tambahkan semua service di sini

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest ./services/${{ matrix.service }}

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest
